module.exports = {
  "about.js":  require('./about'),
  "avatar-edit.js":  require('./avatar-edit'),
  "avatar-image.js":  require('./avatar-image'),
  "avatar-link.js":  require('./avatar-link'),
  "avatar-name.js":  require('./avatar-name'),
  "avatar-profile.js":  require('./avatar-profile'),
  "avatar.js":  require('./avatar'),
  "compose.js":  require('./compose'),
  "feed.js":  require('./feed'),
  "follow.js":  require('./follow'),
  "invite.js":  require('./invite'),
  "like.js":  require('./like'),
  "markdown.js":  require('./markdown'),
  message: {
    author:    require('./message/author'),
    backlinks: require('./message/backlinks'),
    link:      require('./message/link'),
    name:      require('./message/name'),
    render:    require('./message/render'),
  },
  "names.js":  require('./names'),
  "post.js":  require('./post'),
  "private.js":  require('./private'),
  "pub.js":  require('./pub'),
  "public.js":  require('./public'),
  "relationships.js":  require('./relationships'),
  "reply.js":  require('./reply'),
  "search-box.js":  require('./search-box'),
  "setup.js": require('./setup'),
  "suggest-mentions.js":  require('./suggest-mentions'),
  "thread.js":  require('./thread'),
  "timestamp.js":  require('./timestamp')
}

