module.exports = {
  "about.js":  require('./about.js'),
  "avatar-edit.js":  require('./avatar-edit.js'),
  "avatar-image.js":  require('./avatar-image.js'),
  "avatar-link.js":  require('./avatar-link.js'),
  "avatar-name.js":  require('./avatar-name.js'),
  "avatar-profile.js":  require('./avatar-profile.js'),
  "avatar.js":  require('./avatar.js'),
  "compose.js":  require('./compose.js'),
  "feed.js":  require('./feed.js'),
  "follow.js":  require('./follow.js'),
  "invite.js":  require('./invite.js'),
  "like.js":  require('./like.js'),
  "markdown.js":  require('./markdown.js'),
  "message-link.js":  require('./message-link.js'),
  "message-name.js":  require('./message-name.js'),
  "message.js":  require('./message.js'),
  "names.js":  require('./names.js'),
  "post.js":  require('./post.js'),
  "private.js":  require('./private.js'),
  "public.js":  require('./public.js'),
  "relationships.js":  require('./relationships.js'),
  "search-box.js":  require('./search-box.js'),
  "suggest-mentions.js":  require('./suggest-mentions.js'),
  "suggest.js":  require('./suggest.js'),
  "thread.js":  require('./thread.js'),
  "timestamp.js":  require('./timestamp.js')
}
